# Generated by Django 5.0.3 on 2024-04-24 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamation',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='contenu',
        ),
        migrations.AddField(
            model_name='reclamation',
            name='description',
            field=models.TextField(default='Your default description here', max_length=100),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='recl_type',
            field=models.CharField(choices=[('Payment', 'Payment Issue'), ('Posts', 'Posts Issue'), ('Other', 'Other Issue')], default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='user',
            field=models.ForeignKey(default='Donor', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
