# Generated by Django 5.0.3 on 2024-04-23 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('numCpt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montantDons', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
