# Generated by Django 5.0.4 on 2024-05-13 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0001_initial'),
        ('publications', '0006_alter_publication_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='publications.publication'),
        ),
    ]
