# Generated by Django 5.0.3 on 2024-04-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_publication_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
