# Generated by Django 5.0.3 on 2024-05-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_alter_publication_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
    ]
